version: '3.1'
services:
  # ffmpeg:
  #   container_name: b2c-ffmpeg
  #   image: jrottenberg/ffmpeg
  backend:
    build:
      context: ./flaskr/
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 5000:5000
volumes:
    data_app: {} 